# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Cmd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Cmd.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tCmd.proto*V\n\x0b\x43ommandType\x12\x15\n\x11\x43OMMAND_TYPE_NULL\x10\x00\x12\x17\n\x13\x43OMMAND_TYPE_CLIENT\x10\x01\x12\x17\n\x13\x43OMMAND_TYPE_SERVER\x10\x02\x62\x06proto3')
)

_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='CommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMMAND_TYPE_NULL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_TYPE_CLIENT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_TYPE_SERVER', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=13,
  serialized_end=99,
)
_sym_db.RegisterEnumDescriptor(_COMMANDTYPE)

CommandType = enum_type_wrapper.EnumTypeWrapper(_COMMANDTYPE)
COMMAND_TYPE_NULL = 0
COMMAND_TYPE_CLIENT = 1
COMMAND_TYPE_SERVER = 2


DESCRIPTOR.enum_types_by_name['CommandType'] = _COMMANDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
