# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientCmd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Cmd_pb2 as Cmd__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ClientCmd.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x43lientCmd.proto\x1a\tCmd.proto\"f\n\x08LoginCmd\x12\x19\n\x03\x63md\x18\x01 \x01(\x0e\x32\x0c.CommandType\x12\x1b\n\x05param\x18\x02 \x01(\x0e\x32\x0c.ClientParam\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t*A\n\x0b\x43lientParam\x12\x15\n\x11\x43LIENT_PARAM_NULL\x10\x00\x12\x1b\n\x17\x43LIENT_PARAM_LOGIN_AUTH\x10\x01\x62\x06proto3')
  ,
  dependencies=[Cmd__pb2.DESCRIPTOR,])

_CLIENTPARAM = _descriptor.EnumDescriptor(
  name='ClientParam',
  full_name='ClientParam',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLIENT_PARAM_NULL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLIENT_PARAM_LOGIN_AUTH', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=134,
  serialized_end=199,
)
_sym_db.RegisterEnumDescriptor(_CLIENTPARAM)

ClientParam = enum_type_wrapper.EnumTypeWrapper(_CLIENTPARAM)
CLIENT_PARAM_NULL = 0
CLIENT_PARAM_LOGIN_AUTH = 1



_LOGINCMD = _descriptor.Descriptor(
  name='LoginCmd',
  full_name='LoginCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='LoginCmd.cmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param', full_name='LoginCmd.param', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='LoginCmd.username', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='LoginCmd.password', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=132,
)

_LOGINCMD.fields_by_name['cmd'].enum_type = Cmd__pb2._COMMANDTYPE
_LOGINCMD.fields_by_name['param'].enum_type = _CLIENTPARAM
DESCRIPTOR.message_types_by_name['LoginCmd'] = _LOGINCMD
DESCRIPTOR.enum_types_by_name['ClientParam'] = _CLIENTPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginCmd = _reflection.GeneratedProtocolMessageType('LoginCmd', (_message.Message,), dict(
  DESCRIPTOR = _LOGINCMD,
  __module__ = 'ClientCmd_pb2'
  # @@protoc_insertion_point(class_scope:LoginCmd)
  ))
_sym_db.RegisterMessage(LoginCmd)


# @@protoc_insertion_point(module_scope)
