if(UNIX)
    if( CMAKE_BUILD_TYPE STREQUAL "Debug" )
        set(CMAKE_C_FLAGS  "${CMAKE_C_FLAGS} -fPIC")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -O0 -Wall -g -ggdb -DDEBUG -fPIC")
    else()
        set(CMAKE_BUILD_TYPE "Release")
        set(CMAKE_C_FLAGS  "${CMAKE_C_FLAGS} -fPIC")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -fPIC -std=c++11 -O3 -Wall")
    endif()

    set(LDFLAGS "$ENV{LDFLAGS} -stdlib=libc++")
    #MAC不需要这一行
    if (NOT APPLE)
        add_definitions(-std=c++11)
    endif()
else()
    SET ( CMAKE_CXX_FLAGS "-D_X64 -D_WINDOWS /EHsc" )
endif()